version: 2
jobs:
  build:
    macos:
      xcode: "9.0.1"
    working_directory: /Users/distiller/project
    steps:
      - checkout
      - run:
          name: Update brew
          command: brew update && brew upgrade python
      - run:
          name: Install brew dependencies
          command: brew install cmake p7zip libzip libuv protobuf
      - run:
          name: Install python dependencies
          command: pip3 install jinja2 ds_store
      - run:
          name: Download Qt
          command: ./download_qt.sh
      - run:
          name: Build
          command: python3 __main__.py --qt-path qt/*/*/ --update-url https://mcpelauncher.mrarm.io/ver/osx --build-id $CIRCLE_BUILD_NUM
      - run:
          name: Build .dmg
          command: python3 build_dmg.py
      - store_artifacts:
          path: output/Minecraft Bedrock Launcher.dmg
          destination: /Minecraft Bedrock Launcher.dmg
      - run:
          name: Upload the .dmg to website
          command: 'curl -X POST -u "ci:$WEBSITE_CI_UPLOAD_PASS" --data-binary "@output/Minecraft Bedrock Launcher.dmg" -H "X-Type: osx-dmg" https://mcpelauncher.mrarm.io/api/v1/upload'
      - run:
          name: Update version number
          command: 'curl -X POST -u "ci:$WEBSITE_CI_UPLOAD_PASS" -F "channel=osx" -F "build_id=$CIRCLE_BUILD_NUM" https://mcpelauncher.mrarm.io/api/v1/version'
